name: app_play_basketball
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  #  new dependencies from komvik 06.09.2024
  # flutter:
  # sdk: flutter
 
  # sqflite: ^2.3.3
  # path_provider: ^2.0.11
 

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

